### PR TITLE
Update henry.py

### PR DESCRIPTION
**Pull request by henry-richard**

### CODE REVIEW

**Comment by henry-richard** [comment]
Test

**Comment by sarah-paidpaper** [comment]
GH sync

**Comment by henry-richard** [comment]
**Pullflow{pre-next}** request review **Sarah Thompson**

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by henry-richard** [comment]
🔍 [Review requested](https://github.com/PaidPaper/public-4/pull/58) from [sarah-paidpaper](https://github.com/sarah-paidpaper)

**Comment by wanda-carlson** [comment]
Tset

**Pull request merged**
