### PR TITLE
Update henry.py

### PR DESCRIPTION
**Pull request by henry-richard**
Testing

### CODE REVIEW

**Comment by henry-richard** [comment]
Test

**Comment by henry-richard** [comment]
**Test**
**Test**
_Test_
~Test~
1. Test
* Test
>Test
`Test`
```
Test
Test
```

**Comment by henry-richard** [comment]
@bert-griffin @sarah-paidpaper ?

**Comment by henry-richard** [comment]
**Sarah Thompson** @bert-griffin ?

**Comment by henry-richard** [comment]
### Test
**Test**
_Test_
`Test`
[Test](https://github.com/PaidPaper/public-4/pull/100)

1. Test

- Test

- [ ] Test

```
Test
Test
```

**Comment by henry-richard** [comment]
TEst

**Review by wanda-carlson — APPROVED** [review]

**Pull request merged**
